# Работа с текстовыми данными

Задание: Обучите модель для определения принадлежности текста к одному из заданных классов. При разборе текста используйте Bag of words.

Файлы данных см. по ссылке - https://disk.yandex.ru/d/HHKOvuZqKmcmbw

## Обработка естественного языка или **NLP (Natural Language Processing)**

NLP занимается применением алгоритмов Machine Learning для текстовых данных.

*Основные определения:*

Сначала текст разбивается на **текстовые единицы (токены)**, например, символы, слова, словосочетания, предложения, абзацы и т.д. Чаще всего разбивают на слова. Токены образуют **словарь**, который может быть отсортирован по алфавиту.
Также в NLP применяются термины «документ» и «корпус». **Документ** — это совокупность токенов, которые принадлежат одной смысловой единице. В качестве документа может выступать предложение, комментарий или пост пользователя. **Корпус** — это генеральная совокупность всех документов.

Как вы уже знаете, алгоритмы машинного обучения работают с числами. Соответственно, нам нужно придумать, как представить наш текст с помощтю чисел.

### Bag-of-words

Bag of Words или мешок слов — это модель, часто используемая при обработке текстов, представляющая собой неупорядоченный набор слов, входящих в обрабатываемый текст. Это одна из самых простых методик векторизации текста. В логике BOW два предложения могут называться одинаковыми, если содержат один и тот же набор слов.

BOW широко используется для решения следующих задач:

1. Обработка естесственного языка
2. Получение информации из документов
3. Классификация документов.


Глобально работа этого алгоритма состоит из следующих шагов:

![image.png]()![image.png](attachment:image.png)

[Источник](https://www.freecodecamp.org/news/an-introduction-to-bag-of-words-and-how-to-code-it-in-python-for-nlp-282e87a9da04/)

Сгенерированные векторы можно использовать в качестве входных данных для машинного обучения.

Рассмотрим пример. Возьмём два предложения:

1. *"John likes to watch movies. Mary likes movies too."*
2. *"John also likes to watch football games."*

Эти два предложения также могут быть представлены набором слов.

1. *['John', 'likes', 'to', 'watch', 'movies.', 'Mary', 'likes', 'movies', 'too.']*
2. *['John', 'also', 'likes', 'to', 'watch', 'football', 'games']*

Преобразуем эти наборы в словари:

1. *{"John":1,"likes":2,"to":1,"watch":1,"movies":2,"Mary":1,"too":1}*
2. *{"John":1,"also":1,"likes":1,"to":1,"watch":1,"football":1,   "games":1}*

Пусть эти предложения являются частью большого документа. Тогда общий словарь будет выглядеть так:

{"John":2,
"likes":3,
"to":2,
"watch":2,
"movies":2,
"Mary":1,
"too":1,  
"also":1,
"football":1,
"games":1}

Этот словарь всех слов в документе и будет использоваться для создания векторов для каждого предложения.

**Важно**: длина вектора всегда равна длине словаря! В данном случае, длина вектора равна 10.

Таким образом, векторы наших предложений будут выглядеть так:

1. *John likes to watch movies. Mary likes movies too.* => [1, 2, 1, 1, 2, 1, 1, 0, 0, 0]
2. *John also likes to watch football games.* => [1, 1, 1, 1, 0, 0, 0, 1, 1, 1]

**Важно**: в предложении 1 слово "likes" стоит на второй позиции и встречается два раза. Таким образом, второй элемент нашего вектора для предложения 1 будет равен 2.

Большой документ, в котором сгенерированный словарь огромен, может привести к созданию вектора с множеством нулевых значений. Это называется разреженным вектором . Разреженные векторы требуют больше памяти и вычислительных ресурсов при моделировании. Огромное количество позиций или размеров может сделать процесс моделирования очень сложным для традиционных алгоритмов.

![image.png](https://dudeperf3ct.github.io/images/lstm_and_gru/bag-of-words.png)

[Источник](https://dudeperf3ct.github.io/lstm/gru/nlp/2019/01/28/Force-of-LSTM-and-GRU/)

Этапы алгоритма:

### Шаг 1. Токенизация предложения.

Начнем с удаления стоп-слов из предложений.

**Стоп-слова** — это слова, которые не содержат достаточного значения для использования без нашего алгоритма. Нам бы не хотелось, чтобы эти слова занимали место в нашей базе данных или отнимали ценное время обработки. Для этого мы можем легко удалить их, сохранив список слов, которые вы считаете стоп-словами. В нашем случае, мы будем использовать библиотеку nltk .  В ней уже есть набор предопределенных стоп-слов для каждого языка.

**Токенизация** — это процесс разбиения последовательности строк на части, такие как слова, ключевые слова, фразы, символы и другие элементы, называемые токенами . Токенами могут быть отдельные слова, фразы или даже целые предложения. В процессе токенизации некоторые символы, например знаки препинания, отбрасываются.




### Шаг 2. Примените токенизацию ко всем предложениям

Метод перебирает все предложения и добавляет извлеченное слово в массив.




### Шаг 3. Создайте словарный запас и создайте векторы

Используйте методы, определенные в шагах 1 и 2, чтобы создать словарь документа и извлечь слова из предложений.

Понимание Bag-of-words:

Модель BOW учитывает только то, встречается ли известное слово в документе или нет. Его не волнуют смысл, контекст и порядок, в котором они появляются.
Это дает представление о том, что аналогичные документы будут иметь одинаковое количество слов. Другими словами, чем более похожи слова в двух документах, тем более похожими могут быть документы.

Ограничения BoW:

1. Семантическое значение : базовый подход BOW не учитывает значение слова в документе.

2. Размер вектора . Для большого документа размер вектора может быть огромным, что потребует большого количества вычислений и времени.

In [162]:
# установим библиотеку, содержащую стоп-слова
%pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk) (2024.9.11)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from nltk) (4.66.6)

In [163]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import HashingVectorizer
from nltk.corpus import stopwords
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import roc_curve, roc_auc_score

import matplotlib.pyplot as plt
import seaborn as sns

In [164]:
data1 = pd.read_csv('/content/DataSet13_2_1.csv', sep=';',  encoding='UTF-8')

In [165]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 224813 entries, 0 to 224812
Data columns (total 16 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   № материала           224813 non-null  int64
 1   Содержание материала  175239 non-null  object
 2   Дата публикации       224813 non-null  object
 3   Тип документа         224813 non-null  object
 4   Источник              224813 non-null  object
 5   Дубликатов            224813 non-null  int64
 6   Репостов              224813 non-null  int64
 7   Лайков                224813 non-null  int64
 8   Просмотров            224813 non-null  int64
 9   Комментариев          224813 non-null  int64
 10  Регион                224813 non-null  object
 11  Район                 67094 non-null   object
 12  Город                 224813 non-null  object
 13  Возраст               224813 non-null  int64
 14  Друзей                224813 non-null  int64
 15  Подписчиков           224813 non-null  int64
dtypes: int64(9), object(7)
memory usage: 27.4+ MB

In [166]:
data2 = pd.DataFrame({
    'ID': data1['№ материала'],
    'Text': data1['Содержание материала'],
    'TDate': data1['Дата публикации'],
    'TType': data1['Тип документа'],
    'TSource': data1['Источник'],
    'TDouble': pd.to_numeric(data1['Дубликатов']),
    'TRepost': pd.to_numeric(data1['Репостов']),
    'TLike': pd.to_numeric(data1['Лайков']),
    'TView': pd.to_numeric(data1['Просмотров']),
    'TComment': pd.to_numeric(data1['Комментариев']),
    'TRegion': data1['Регион'],
    'TRayon': data1['Район'],
    'TCity': data1['Город'],
    'TAge': pd.to_numeric(data1['Возраст']),
    'TFriend': pd.to_numeric(data1['Друзей']),
    'TReader': pd.to_numeric(data1['Подписчиков'])
})

del data1 # удалим датафрейм data1, чтобы он не занимал место в памяти компьютера, он достаточно объёмный

In [167]:
data2.head()

,ID,Text,TDate,TType,TSource,TDouble,TRepost,TLike,TView,TComment,TRegion,TRayon,TCity,TAge,TFriend,TReader
0,1,NaN,2021-02-08,Пост,Пользователь,0,1,20,124,1,Пермский край,NaN,Пермь,23,54,126
1,2,"Если спросят ""Счастье где?""... \nЯ отвечу - ""В...",2021-02-08,Пост,Пользователь,0,0,9,285,0,Пермский край,NaN,Пермь,19,83,40
2,3,NaN,2021-02-12,Репост,Пользователь,0,0,0,0,0,Пермский край,NaN,Березники,31,103,13
3,4,#фото_дня@serial_sled ⚬ #съёмки@serial_sled\n#...,2021-02-12,Репост,Пользователь,0,0,0,0,0,Пермский край,NaN,Березники,31,103,13
4,5,#gif #открытки #картинки #природа,2021-02-08,Репост,Пользователь,6,0,0,0,0,Пермский край,NaN,Березники,31,103,13

In [168]:
# Преобразуем текстовое поле с датой в тип даты
data2["TDate"] = pd.to_datetime(data2["TDate"])

In [169]:
data2 = data2.dropna()

In [170]:
# Читаем файл с классами

data_classes = pd.read_csv(r"/content/DataSet13_2_2.csv",  sep=";", encoding="UTF-8")
data_classes2 = pd.DataFrame({
    "Text": data_classes["Содержание материала"],
    "TClass": data_classes["Разметка"]
})
del data_classes
data_classes2 = data_classes2.dropna()

In [171]:
#Склеиваем переменные с данными и классами

df = pd.merge(data2, data_classes2, on="Text", how="inner")
del data_classes2, data2

In [172]:
len(df['TClass'].unique())

89

### Классификация

89 классов.

Сейчас все метки классов закодированы текстом.

In [173]:
# проверьте метки классов

Для решения задачи классификации нам нужно перекодировать текст в числа. Можно это сделать с помощью словаря, но удобнее использовать LabelEncoder

In [174]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['TClass'] = le.fit_transform(df['TClass'])

In [175]:
max(df['TClass'].unique())

88

In [176]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23361 entries, 0 to 23360
Data columns (total 17 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        23361 non-null  int64
 1   Text      23361 non-null  object
 2   TDate     23361 non-null  datetime64[ns]
 3   TType     23361 non-null  object
 4   TSource   23361 non-null  object
 5   TDouble   23361 non-null  int64
 6   TRepost   23361 non-null  int64
 7   TLike     23361 non-null  int64
 8   TView     23361 non-null  int64
 9   TComment  23361 non-null  int64
 10  TRegion   23361 non-null  object
 11  TRayon    23361 non-null  object
 12  TCity     23361 non-null  object
 13  TAge      23361 non-null  int64
 14  TFriend   23361 non-null  int64
 15  TReader   23361 non-null  int64
 16  TClass    23361 non-null  int64
dtypes: datetime64[ns](1), int64(10), object(6)
memory usage: 3.0+ MB

In [177]:
df = df.dropna()

In [178]:
pd.set_option('display.max_rows', None)

Классов очень много, а данных не так много. Давайте посмотрим, распределение данных по классам:

In [179]:
df.groupby('TClass')['Text'].count().sort_values(ascending=False)

TClass
5     6353
77    3546
48    2304
63    1406
80    1130
11     818
86     690
12     640
59     576
9      459
21     400
56     376
2      322
27     302
55     294
46     258
81     255
7      222
75     220
13     184
85     160
73     147
37     143
10     141
83     128
16     120
28     100
62      96
66      90
40      90
17      84
68      78
54      76
51      72
8       70
60      69
88      57
61      50
82      50
31      49
30      49
84      49
64      49
78      49
65      40
36      40
67      40
22      30
34      25
57      25
6       24
35      22
45      21
29      18
39      18
72      16
47      16
18      16
23      16
38      16
25      14
79      12
20      12
44       9
50       9
43       9
41       9
19       8
3        7
53       6
33       6
4        5
58       4
15       4
26       4
76       4
42       4
1        4
52       4
70       3
69       3
49       3
74       2
32       2
71       2
24       2
14       2
87       2
0        2
Name: Text, dtype: int64

In [181]:
#Сводим к задаче бинарной классификации

# df.loc[df['TClass'] != 5, 'TClass'] = 0
# df.loc[df['TClass'] == 5, 'TClass'] = 1

In [182]:
df['Text'] = df['Text'].str.replace("\"", "")
df['Text'] = df['Text'].str.replace("\n", "")
# df['Text']

In [183]:
# подготовка текста
corpus = df['Text'].tolist()

In [184]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [185]:
# Предобработка текста
stop_words = stopwords.words("russian")
vectorizer = CountVectorizer(lowercase=True, stop_words=stop_words, min_df=3)
# CountVectorizer автоматически токенизует корпус и создаёт словарь из всех слов
X = vectorizer.fit_transform(corpus)
y = df['TClass']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [186]:
# Train the model
model = LinearSVC()
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1235: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

In [187]:
# Calculate evaluation metrics
# conf_matrix = confusion_matrix(y_test, y_pred)
# plt.figure(figsize=(6, 4))
# sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues', cbar=False)
# plt.xlabel('Predicted')
# plt.ylabel('Actual')
# plt.title('Confusion Matrix')
# plt.show()

In [188]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.00      0.00      0.00         0
           2       0.67      1.00      0.80        66
           3       0.00      0.00      0.00         0
           4       1.00      1.00      1.00         1
           5       1.00      1.00      1.00      1279
           6       1.00      1.00      1.00         5
           7       1.00      1.00      1.00        55
           8       1.00      1.00      1.00        17
           9       1.00      1.00      1.00        98
          10       1.00      1.00      1.00        30
          11       0.98      0.94      0.96       150
          12       1.00      1.00      1.00       126
          13       0.00      0.00      0.00        32
          14       1.00      1.00      1.00         1
          15       1.00      1.00      1.00         1
          16       1.00      1.00      1.00        24
          17       1.00      1.00      1.00        20
          18       1.00      1.00      1.00         4
          19       1.00      1.00      1.00         2
          20       1.00      1.00      1.00         4
          21       1.00      1.00      1.00        70
          22       1.00      1.00      1.00         8
          23       1.00      1.00      1.00         3
          24       1.00      1.00      1.00         1
          25       1.00      0.67      0.80         3
          27       1.00      1.00      1.00        67
          28       0.00      0.00      0.00        19
          29       0.00      0.00      0.00         2
          30       1.00      1.00      1.00        13
          31       1.00      1.00      1.00         9
          32       1.00      1.00      1.00         1
          34       1.00      1.00      1.00         2
          35       1.00      1.00      1.00         5
          36       1.00      1.00      1.00         8
          37       1.00      1.00      1.00        17
          38       1.00      1.00      1.00         1
          39       1.00      1.00      1.00         5
          40       1.00      1.00      1.00        17
          41       1.00      1.00      1.00         1
          42       0.00      0.00      0.00         1
          43       1.00      1.00      1.00         2
          44       0.00      0.00      0.00         1
          45       1.00      1.00      1.00         3
          46       1.00      1.00      1.00        54
          47       0.00      0.00      0.00         3
          48       1.00      1.00      1.00       476
          50       1.00      1.00      1.00         3
          51       1.00      1.00      1.00        15
          54       1.00      1.00      1.00        13
          55       1.00      1.00      1.00        60
          56       1.00      1.00      1.00        67
          57       1.00      1.00      1.00         5
          58       1.00      1.00      1.00         1
          59       1.00      1.00      1.00       110
          60       1.00      1.00      1.00        17
          61       1.00      1.00      1.00        14
          62       1.00      1.00      1.00        15
          63       1.00      1.00      1.00       277
          64       1.00      1.00      1.00         8
          65       1.00      1.00      1.00        11
          66       1.00      1.00      1.00        24
          67       1.00      1.00      1.00         7
          68       1.00      1.00      1.00        15
          69       0.00      0.00      0.00         1
          72       1.00      1.00      1.00         3
          73       0.00      0.00      0.00        29
          75       1.00      1.00      1.00        45
          76       1.00      1.00      1.00         3
          77       0.99      1.00      1.00       723
          78       1.00      1.00      1.00        11
          79       1.00      1.00      1.00         2
          80       0.76      1.00      0.87       211
          81       1.00      1.00      1.00        47
          82       0.00      0.00      0.00        10
          83       1.00      1.00      1.00        24
          84       1.00      1.00      1.00        10
          85       1.00      1.00      1.00        21
          86       1.00      1.00      1.00       146
          87       1.00      1.00      1.00         1
          88       1.00      1.00      1.00        17

    accuracy                           0.98      4673
   macro avg       0.86      0.86      0.86      4673
weighted avg       0.96      0.98      0.97      4673

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))